name: Auto Test

on:
    push:
    pull_request:

jobs:
    test:
        name: Test @${{ matrix.os }} / Node.js-${{ matrix.node }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node: [18, 20, 22, 'latest']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Install root dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Install test dependencies
              working-directory: tests
              run: npm install

            - name: Run tests
              working-directory: tests
              run: node .
